export const LOGIN_IN_PROGRESS = 'LOGIN'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const RESET_CURRENT_USER = 'RESET_CURRENT_USER'
export const FINISH_AUTH = 'FINISH_AUTH'
export const SET_TOKEN = 'SET_TOKEN'
